### ISSUE TITLE
[TD-100] Log taskd messages to stdout if launched by systemd

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#100]
_Sebastien Badia on 2015-07-16T12:47:21Z says:_ 

 Hi,

Since https://bug.tasktools.org/browse/TD-63 and https://bug.tasktools.org/browse/TD-41 are now merged, it was maybe interesting to change default to logging to stdout (and hence to journalctl), if taskd server was launched by systemd.

Seb

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-07-16T12:47:21Z
Modified: 2015-12-23T13:14:31Z
```

**Comment by taskwarrior** [comment]
_Sebastien Badia on 2015-12-22T20:54:43Z says:_ 

 Debian Packaging patch

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-12-23T13:14:31Z says:_ 

 Patch applied, thank you.

**Comment by pbeckingham** [comment]
[TD-100_log-to-stdout.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755317/TD-100_log-to-stdout.patch.txt)
