### ISSUE TITLE
[TD-102] After creating a user aparently successful taskd says: User does not exists

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#102]
_Olaf H B on 2015-08-19T00:54:50Z says:_ 

 Can't sync taskwarrior with taskd.

After following the instructions in the instalation and config guide for client and server I receive this in client:

bq. Sync failed. Either your credentials are incorrect, or your Taskserver account is not enabled.

After a lot of tries I discover that taskd create the user apparently fine but if I try to remove it after it says : User does not exist

**Comment by pbeckingham** [comment]
![td-102_20150818_195210](https://user-images.githubusercontent.com/7963/36635402-2070af9e-1982-11e8-8fb8-01ab12368e37.jpg)
[TD-102_taskd_diagnostics.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755316/TD-102_taskd_diagnostics.txt)

**Comment by darukutsu** [comment]
issue persist on `freebsd 13.1-RELEASE-p5` `taskd 1.1.0`. 
I can create same user succesfully infinite number of time but can't remove any even if 1 entry.
```
root@freebsd:/usr/local/share/taskd # cat /var/db/taskd/orgs/Public/users/b7de7f86-4649-11ee-a5df-e0d55e54ea65/config
user=daru
root@freebsd:/usr/local/share/taskd # cat /var/db/taskd/orgs/Public/users/d411caf7-464c-11ee-a5df-e0d55e54ea65/config 
user=daru
root@freebsd:/usr/local/share/taskd # taskd remove user 'Public' 'daru'
ERROR: User 'daru' does not  exists.
```

**taskd diagnostics:**
```
taskd 1.1.0
    Platform: FreeBSD
    Hostname: freebsd.daruserver

Compiler
     Version: FreeBSD Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
        Caps: +stdc +stdc_hosted +200112 +LP64 +c8 +i32 +l64 +vp64 +time_t64
  Compliance: C++11

Build Features
       Built: Jul  9 2023 02:58:15
       CMake: 3.26.1
     libuuid: libuuid, no uuid_unparse_lower
   libgnutls: 3.7.9
  Build type: Release

Configuration
   TASKDDATA: /var/db/taskd
        root: /var/db/taskd (readable)
      config: /var/db/taskd/config (readable)
          CA: /var/db/taskd/ca.cert.pem (readable)
 Certificate: /var/db/taskd/server.cert.pem (readable)
         Key: /var/db/taskd/server.key.pem (readable)
         CRL: /var/db/taskd/server.crl.pem (readable)
         Log: /var/log/taskd.log (found)
    PID File: /tmp/taskd.pid (found)
      Server: 192.168.0.116:53589
 Max Request: 1048576 bytes
     Ciphers: 
       Trust: allow all
```
