### ISSUE TITLE
[TD-103] Incorrect Error Message when Org does not exist

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#103]
_Jack on 2015-08-27T23:47:08Z says:_ 

 When no organizations have been created, and I issue the command:

{code}
taskd add user 'FreeCinc' 'freecinc_35ec5c11' --data /home/vagrant/taskddata
{code}

I get the error:
{code}
ERROR: Organization 'user' does not exist.
{code}

The error I *should* get is:

{code}
ERROR: Organization 'FreeCinc' does not exist.
{code}

**Comment by pbeckingham** [comment]
[TD-103_0001-Incorrect-error-when-org-does-not-exists.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755315/TD-103_0001-Incorrect-error-when-org-does-not-exists.patch.txt)
