### ISSUE TITLE
[TD-105] Taskd reports wrong error on misformatted data (tabs)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#105]
_Jack Laxson on 2015-10-26T22:20:26Z says:_ 

 https://gist.github.com/jrabbit/3dd6cd1835d6aa421fed note the tabs on the second and third tasks

relevant code:
https://git.tasktools.org/projects/TM/repos/taskd/browse/src/daemon.cpp#559

expected outcome:
error 500 but correct error message

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-10-26T22:20:26Z
Modified: 2017-01-17T03:09:49Z
```

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
