### ISSUE TITLE
[TD-108] Make taskd build reproductible (remove binary timestamps)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#108]
_Sebastien Badia on 2015-12-22T21:03:32Z says:_ 

 In Debian, and more generally it's better to have a reproductible build :-)

In order to make the build reproductive we need to avoid all dynamic generated var (like date).

Thanks!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-22T21:03:32Z
Modified: 2017-01-17T03:10:33Z
```

**Comment by taskwarrior** [comment]
_Sebastien Badia on 2015-12-22T21:04:48Z says:_ 

 Patch for reproductible builds

**Comment by pbeckingham** [comment]
[TD-108_remove-date-time.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755314/TD-108_remove-date-time.patch.txt)

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
