### ISSUE TITLE
[TD-9] taskd should include option to list users (optionally by org/group)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#11]
_Renato Alves on 2014-01-22T18:23:55Z says:_ 

 Currently taskd includes options to add/remove users but not to list/show existing ones.

The only way one can get that information is by inspecting $TASKDDATA/org which is bound to cause problems if tampered with.

I suggest that an option to list users with the following command signatures:

```
taskd list user <org> [<user>]
taskd list group <org> [<group>]
```

which lists users/groups by org, filtering down to users/groups matching <user/group> if given

```
taskd list org [<org>]
```

to list all existing orgs, optionally filtering by <org>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-01-22T18:23:55Z
Modified: 2016-11-26T16:17:41Z
```

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
