### ISSUE TITLE
[TD-114] Allow taskd to listen on IPv4 and IPv6 simultaneously 

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#114]
_Wade Duvall on 2016-03-23T13:23:00Z says:_ 

 I would like the ability to have taskd listen on both IPv4 and IPv6 so that I can continue supporting IPv6 while also connecting over IPv4 from locations which don't yet offer IPv6 connections.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-03-23T13:23:00Z
Modified: 2017-10-12T02:24:23Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-03-23T13:30:43Z says:_ 

 This is from the ChangeLog for 1.2.0:

bq. - Added dual-stack IPv4/IPv6 support, when the IPv6 address is specified as :: which means a confguration setting of server=:::<someport>. Related to TD-51 (thanks to Johannes Wienke).

**Comment by taskwarrior** [comment]
_Adam Chasen on 2017-08-28T15:42:47Z says:_ 

 consider updating: https://taskwarrior.org/docs/taskserver/protocol.html

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-10-12T02:24:23Z says:_ 

 Send a patch.

**Comment by madduck** [comment]
Cf. #128

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
