### ISSUE TITLE
[TD-116] Provided systemd unit file does not match recommended systemd unit file in docs

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#116]
_Wade Duvall on 2016-04-04T14:29:10Z says:_ 

 scripts/systemd/taskd.service does not match what is recommended in the documentation here: https://taskwarrior.org/docs/taskserver/control.html. The documented version seems to have some security improvements. Patch provided.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-04-04T14:29:10Z
Modified: 2016-12-19T15:15:07Z
```

**Comment by taskwarrior** [comment]
_Wade Duvall on 2016-04-04T14:30:18Z says:_ 

 If it turns out that the changes are not necessarily, please turn this into a documentation improvement.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-04-09T19:24:28Z says:_ 

 Are these suggested directory names portable?  I think they are not.

**Comment by taskwarrior** [comment]
_Wade Duvall on 2016-04-09T19:32:29Z says:_ 

 /var/lib/taskd is already hardcoded into the provided unit file. I am not a systemd expert so I don't know what happens if any of the InaccessibleDirectories don't exist, but I think those exist on most linux systems.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-12-19T15:15:07Z says:_ 

 Patch applied.  Thank you.

**Comment by pbeckingham** [comment]
[TD-116_taskd.service.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755312/TD-116_taskd.service.patch.txt)
