### ISSUE TITLE
[TD-117] Wrong systemd target, taskd can fail if multi-user.target is up earlier than the network

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#117]
_Sebastian Sonne on 2016-04-09T17:37:58Z says:_ 

 So far, taskd.service has "WantedBy=multi-user.target", however there are servers where multi-user is up earlier than the network. Thus, taskd doesn't get an IP, FQDN etc. and completely fails.

Patch attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-04-09T17:37:58Z
Modified: 2016-04-09T17:54:17Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-04-09T17:54:17Z says:_ 

 Thank you!

**Comment by pbeckingham** [comment]
[TD-117_taskd.service.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755311/TD-117_taskd.service.patch.txt)
