### ISSUE TITLE
[TD-119] Build fails on Debian (no C++11 support)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#119]
_Samathy Barratt on 2016-05-01T13:40:19Z says:_ 

 Cmake fails complaining about lack of c++11 support, despite G++ version 4.7.2.

Removing cmake's checks for C++ version means build runs, but fails completely.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-05-01T13:40:19Z
Modified: 2016-06-25T20:10:23Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-05-01T17:55:26Z says:_ 

 Which version are you building?

**Comment by taskwarrior** [comment]
_Samathy Barratt on 2016-05-01T20:33:32Z says:_ 

 I cloned straight form the git repo today, and switched to the master branch.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-06-25T20:09:56Z says:_ 

 Please reclone, and switch to the 1.2.0 branch.  This has C++11 support.  Please let me know if this fails, and I will reopen this issue.

**Comment by pbeckingham** [comment]
[TD-119_CMakeError.log.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755310/TD-119_CMakeError.log.txt)
