### ISSUE TITLE
[TD-122] Taskd should complain/warn if running with an expired certificate

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#122]
_Renato Alves on 2016-05-08T00:08:37Z says:_ 

 At some point in time all the clients of my taskd server stopped syncing.

The error on the client side was:
```
Handshake failed.  Error in the certificate.
Sync failed.  Could not connect to the Taskserver.
```
while on the server the logs only mentioned:
```
Error: Handshake failed. The TLS connection was non-properly terminated.
```
In addition when syncing with "Taskwarrior for android" the server logged:
```
Error: Handshake failed. No certificate was found.
```

None of these messages hinted that the error was due to expired certificates. In this particular situation both server and client certificates expired as they were all generated around the same time.

If possible, the logged message on the server side should contain clearer information on the cause of the failure.

Additionally it would be helpful if taskd logs a warning provided certificates are no longer valid, that they are about to expire or have expired already. This could be done at startup. periodically or just before/after sync.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-05-08T00:08:37Z
Modified: 2016-05-08T14:46:29Z
```

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
