### ISSUE TITLE
[TD-11] pki/generate.client takes arguments

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#13]
_make fu on 2014-01-21T12:15:16Z says:_ 

 Make generate.client more genereric by taking positional arguments for naming client certificate output. E.g.:
1.  current implementation
$ ./generate.client 
output: client.key.pem, client.cert.pem
1.  additional parameter
$ ./generate.client newuser
output: newuser.key.pem, newuser.cert.pem

I attached the respective patch

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-01-21T12:15:16Z
Modified: 2014-02-09T01:34:53Z
```

**Comment by taskwarrior** [comment]
_make fu on 2014-01-21T12:23:11Z says:_ 

 sorry, i was too over-enthusiastic, the code below is already doing what i was looking for...

if [ $# -gt 0 ] ; then
  NAME=$1
fi

this issue can be closed.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-21T12:57:29Z says:_ 

 Yes, the script already does this.  But thank you for taking the time to report and patch - much appreciated.

**Comment by pbeckingham** [comment]
[TD-11_generate.client.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755340/TD-11_generate.client.patch.txt)
