### ISSUE TITLE
[TD-131] Disabled taskd user from logging in

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#130]
_Jethro Lising on 2017-05-13T13:16:47Z says:_ 

 On the taskd install guide on the website, the user taskd is not restricted. Anyone can login as taskd and access tasks at the datadir.

Just simply lock the account to improve security:
passwd -l taskd

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-05-13T13:16:47Z
Modified: 2017-12-03T07:35:56Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-10-12T02:41:06Z says:_ 

 Send a patch for the documentation.

**Comment by taskwarrior** [comment]
_Jethro Lising on 2017-10-12T23:32:19Z says:_ 

 Forgot my old account. The guide on the git repos seem to be outdated, so I just uploaded the relevant addition for security improvement

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2017-12-03T07:35:56Z says:_ 

 Even though it is a good advice, I do not think the taskserver-setup guide is the right place for it.

We do not explain how to create a taskd-user and how to secure this one.

**Comment by pbeckingham** [comment]
[TD-131_taskserver-setup.tex.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755308/TD-131_taskserver-setup.tex.txt)

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
