### ISSUE TITLE
[TD-135] Support illumos (non gnu-which) in PKI scripts

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#134]
_Thomas on 2017-08-27T10:51:56Z says:_ 

 The `which` command is different on all operating system from Linux to *BSD and illumos (SunOS). For that reason the following command result in an error:
{code:java}
CERTTOOL=$(which gnutls-certtool || which certtool){code}
Because `which` on illumos always output the lookup path at `stdout`.
{code:java}
$ CERTTOOL=$(which gnutls-certtool || which certtool)
$ echo ${CERTTOOL}
no gnutls-certtool in /usr/local/sbin /usr/local/bin /opt/local/sbin /opt/local/bin /usr/sbin /usr/bin /sbin /opt/local/bin/certtool{code}
 Affected shell scripts:
 * `pki/generate.ca`
 * `pki/generate.client`
 * `pki/generate.crl`
 * `pki/generate.server`

Recommendation:

 Replace `which` with `type -p` or create a full `if`-query with output redirection.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-08-27T10:51:56Z
Modified: 2017-12-10T04:43:29Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-10-12T02:43:08Z says:_ 

 Send a (portable) patch.

**Comment by taskwarrior** [comment]
_Thomas on 2017-10-13T11:17:35Z says:_ 

 I've attached attached a patch ( [^0001-Posix-compatibility-for-pki-shell-scripts.patch] ) which provide the most portable and POSIX compatibility. If you have any question feel free to contact me.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-10T04:43:29Z says:_ 

 This patch was generated against either the master or 1.1.0 branch (same thing) and is already released.  The development branch is 1.2.0, which already has this kind of portability fix on it.

**Comment by pbeckingham** [comment]
[TD-135_0001-Posix-compatibility-for-pki-shell-scripts.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755307/TD-135_0001-Posix-compatibility-for-pki-shell-scripts.patch.txt)
