### ISSUE TITLE
Share project items, or items tagged

### ISSUE THREAD

**Issue by madduck** [GothenburgBitFactory/taskserver#137]
Hey,

It's probably a long shot, but I still want to get the idea here…

Currently, taskd stores task per user/org. This means that everyone has their own task list, which makes a lot of sense, but also means that it requires out-of-band sync between people co-working on the same task.

Would it be worth to think about how I could share tasks between people? I.e. I might want to share all tasks `project:foo and +ux` with Alex, and all tasks `+home or +kids` with my partner.

There is a myriad of considerations in this, and I'm happy to explore some of them, but I'd first appreciate an initial response to the idea.

Thanks,
martin

**Comment by pbeckingham** [comment]
This is something that has always been wanted, and was recently discussed.  While sharing is difficult, we are considering transfer/delegation and the notion of shared lists on the server.

**Comment by madduck** [comment]
What's the problem with sharing? Concurrent access? Or that the server-side data model just doesn't let you do that right now?

Could you please point me to the recent discussion?

**Comment by nimakro** [comment]
Any news on this, I would love to have that feature...

**Comment by jahagirdar** [comment]
A Simple implementation for this feature would be,

Whenever a task is assigned to a user, keep the original in the owners task folder and create a symlink (ln -s) in the delegate's folder.

Whenever a task delegation is changed, remove the symlink from the old delegate and create them for the new delegates..

* Is this an acceptable solution i.e. will you accept a PR ?
* Which file in the Code base needs to be modified for this?

**Comment by madduck** [comment]
And what if the delegate modifies? Symlinks are very brittle…

**Comment by jahagirdar** [comment]
If the delegate modifies, then I get the modification... Am I missing something here?

My usecase is to '_share_' a task, with both parties able to add comment, re-delegate change status etc.
I understand that others may have a usecase where the delegate can only 'see' the task but not modify it, which wont be supported by symlinks Or they might want fine grained access control over each field which again may not be possible...

But as a simple hack which leapfrogs TW from a personal todolist into a collaborative task management solution simlinks seems to get the job done.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
