### ISSUE TITLE
Mapping certs to config

### ISSUE THREAD

**Issue by reggi** [GothenburgBitFactory/taskserver#140]
Let's encrypt on NGINX gave me the following files.

* `cert.pem`
* `chain.pem`
* `fullchain.pem`
* `key.pem`

The config file has four variables for cert paths.

```
ca.cert
server.cert
server.crl
server.key
```

Can someone please tell me which map to which?

**Comment by timcase** [comment]
`ca.cert=/etc/taskd/ca.cert.pem  (this one you generate by running ./generate.ca)
server.cert=/etc/letsencrypt/live/yoursitedomain/fullchain.pem
server.key=/etc/letsencrypt/live/yoursitedomain/privkey.pem`

You don't need to specify or use server.crl at this point if you are setting up a new server

**Comment by reggi** [comment]
@timcase Ok I believe I have this configured correctly but still having an issue: 

https://github.com/GothenburgBitFactory/taskserver/issues/141
