### ISSUE TITLE
Certificates expire after 1 year

### ISSUE THREAD

**Issue by bodograumann** [GothenburgBitFactory/taskserver#142]
After setting up taskd and distributing the certificates everything works fine for exactly 1 year, until the ca-, server- and client-certs all expire and nothing works anymore.

Not sure if there is a better solution, but I had to generate new certs for those three roles as well as the user (which is luckily only myself), plus redistribute them.

While the `taskd/pki/vars` file contains a `EXPIRATION_DAYS` line, that is not taken into account by the cert generation scripts, except for the revocation list.

Note: https://gitpitch.com/GothenburgBitFactory/taskserver-setup is terrible to read as a slide-show. I very much prefer the simple markdown-document.

**Comment by bodograumann** [comment]
I see now, that this bug is already fixed in the working branch.
Unfortunately the last release is *2 years* old.

Also, given that redistributing certificates is so time consuming, shouldn't the default duration be set longer?

**Comment by jrabbit** [comment]
The defaults are meant to be changed. There isn't however good support for rekeying and maybe that would be something you're interested in? Could you describe that or send a PR that we can look at?

**Comment by pbeckingham** [comment]
When you create the certs/keys, YOU CHOSE how long you wanted them to last.  Choose according to your needs, bearing in mind that certs are intended to expire, it's a best practice.

Not a bug.
