### ISSUE TITLE
Use --sec-param High instead of --bits 4096

### ISSUE THREAD

**Issue by jelly** [GothenburgBitFactory/taskserver#143]
gnutls-certool notes that it would be more future proof to use --sec-param instead of specifiying the exact bits required. Since gnutls-certool can update the required security level, the exact options are:

       --sec-param=str        Specify the security level [low, legacy, medium, high, ultra]

This would replace the BITS=4096 in vars with SEC=high.

--sec-param seems to exists for a while, last reference I could find was in 2014.

**Comment by pbeckingham** [comment]
Good suggestion, thank you.  Fixed.
