### ISSUE TITLE
Add Let's Encrypt certificate server setup to the docs

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [GothenburgBitFactory/taskserver#144]
Start from [here](https://gist.github.com/polettix/e8007a7f2064e7f133d93e060032a880) and [here](https://mrwonko.de/blog/2017/using-letsencrypt-certificates-with-a-taskwarrior-server.html)? Maybe someone else has a better link. I have seen a mention that it was not possible [in the taskserver-setup pitch](https://github.com/GothenburgBitFactory/taskserver-setup/blob/master/PITCHME.md#lets-encrypt). What is true?

**Comment by pbeckingham** [comment]
Until someone puts together a working solution, documents it and provides a pull request it is not true.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
