### ISSUE TITLE
Incorrect Installation README (Version 1.2.0 does not exist on server)

### ISSUE THREAD

**Issue by akwick** [GothenburgBitFactory/taskserver#145]
Problem:
When following the installation routine in the README, I can't download the tar-file for the server as it does not exist (https://taskwarrior.org/download/taskd-1.2.0.tar.gz). 

Solution:
One can fix this issue by changing the version to 1.1.0 (or by providing the version mentioned in the README file).

**Comment by pbeckingham** [comment]
Taskserver 1.2.0 is not released, and therefore does not have a downloadable tarball.
