### ISSUE TITLE
Adding Automation for Taskserver setup

### ISSUE THREAD

**Issue by bvkin** [GothenburgBitFactory/taskserver#150]
Hello,

I was wondering if you guys have considered adding some automation around setting up the server? As it is right now there are quite few manual steps. 

Would be happy to start writing some of it :+1:

**Comment by pbeckingham** [comment]
Have you seen the existing setup automation?  Start there.

**Comment by bvkin** [comment]
No I haven't been able to find it. Is it not pinned on GothenburgBitFactory?
Thanks

**Comment by pbeckingham** [comment]
?  It's in this repository.

**Comment by divagant-martian** [comment]
Hi, I didn't find a reference to this tool in the documentation. Perhaps it would help to add it to the gitpitch, which is where (i think) most of the users go

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
