### ISSUE TITLE
Is there any way to NOT use TLS?

### ISSUE THREAD

**Issue by ghost** [GothenburgBitFactory/taskserver#152]
I am using taskserver at home. So encryption is unnecessary

**Comment by lopter** [comment]
I don't believe there is a way, I tried a while ago, I remember modifying the sources.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
