### ISSUE TITLE
tasks with an "until" date completed in a device and synced after their until date get also deleted

### ISSUE THREAD

**Issue by divagant-martian** [GothenburgBitFactory/taskserver#157]
As the tittle says:

Create a task with an "until" date
Sync
Complete the task before it expires
Wait after expiration date
sync again
Now the task has:
pending -> completed
completed -> deleted

**Comment by btwe** [comment]
FMPOV, that's working as expected, isn't it?

**Comment by divagant-martian** [comment]
I don't think that's the way it should be, a completed task does not get deleted when it has an until..

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
