### ISSUE TITLE
How to find the SOURCEDIR?

### ISSUE THREAD

**Issue by anojo** [GothenburgBitFactory/taskserver#159]
Hello. I hope this project is alive and well, together with the Android apps, which is why I'm trying to install this. 

I am making my attempt at installing TaskServer on Fedora 29, following closely the instructions provided.

I've bumped into steps where they refer to SOURCEDIR, which I think it's the same as the one I'm supposed to find with `find / -name pki -type d`. I could not find any such directory, even though I've installed both taskwarrior and taskd from Fedora repos through `dnf`. The `taskd` command indeed works so I guess the directory is somewhere. How do I find it? How do I move on?

Thanks.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
