### ISSUE TITLE
[TD-14] Copyright string failure

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#16]
_n anooq on 2014-01-06T12:34:48Z says:_ 

 proceeding through taskd/demo/README: I stop after ./run_all because failures were showing. 

I attached the report of run_all, taskd --version and taskd diag.

The one failure "--data" is because I had set TASKDDATA to something weird. I "solved" that by rolling back to taskd default settings and not customizing it at this early stage. The other failure seems to be just that the copyright text shows 2013 instead of 2014.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-01-06T12:34:48Z
Modified: 2014-02-09T02:19:48Z
```

**Comment by taskwarrior** [comment]
_n anooq on 2014-01-06T12:52:51Z says:_ 

 Maybe it's an issue of its own: I had the pleasure to chat with pbeckingham about the "Create Keys and Certs" in taskd/demo/README. 
when I run generate I get: 

./generate.ca: line 5: gnutls-certtool: command not found
chmod: cannot access ‘ca.key.pem’: No such file or directory
./generate.ca: line 18: gnutls-certtool: command not found
chmod: cannot access ‘ca.cert.pem’: No such file or directory
./generate.server: line 5: gnutls-certtool: command not found
chmod: cannot access ‘server.key.pem’: No such file or directory
./generate.server: line 20: gnutls-certtool: command not found
chmod: cannot access ‘server.cert.pem’: No such file or directory
./generate.crl: line 9: gnutls-certtool: command not found
chmod: cannot access ‘server.crl.pem’: No such file or directory
./generate.client: line 10: gnutls-certtool: command not found
chmod: cannot access ‘client.key.pem’: No such file or directory
./generate.client: line 27: gnutls-certtool: command not found
chmod: cannot access ‘client.cert.pem’: No such file or directory

pbeckingham said, somewhere is a version, that finds the correct certtool by itself - and I cannot find it. 
(see report for taskd version and diag).

so, I workaround with $taskd/pki/: sed -i 's/gnutls-certtool/certtool/g' generate.*

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-08T04:05:48Z says:_ 

 The issues you mention (copyright out of date, certtools not found, and TASKDDATA affecting tests) are all known, and the first two are solved.  You are running beta1, which is broken.  I suggest you skip beta2 and go directly to git for the latest code, on the 1.0.0 branch, which I think you'll find works well.

**Comment by pbeckingham** [comment]
[TD-14_report.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755339/TD-14_report.txt)
