### ISSUE TITLE
Question on possible use

### ISSUE THREAD

**Issue by lesar** [GothenburgBitFactory/taskserver#165]
Can TW be use by a team synchronizing by taskserver the tasks using an unique identity and share it on the team users?  
Using tag to assign a task to a team user and sync after every update?  

best regards,
Leonardo

**Comment by jrabbit** [comment]
you'd need to copy the task data at some point with the current tooling.

**Comment by lesar** [comment]
Tank for your response.  
I need some more explain.  

Can I make this:  
install TW on PC1  
install TS on Server  
well configure all.  

synchronize  PC1 on Server
install on TW PC2, PC3, PC4, ... using same user ID of PC1  
let me be more explicative:  
these are identical on PC1, PC2, PC3, PC4, ...
* taskd.key
* taskd.certificate
* taskd.ca
* taskd.credentials
* taskd.server

Then I do: PC1 Sync, PC2 Sync, PC3 Sync,PC4 Sync, .... 

can this work?  
Have to avoid to make PCX Sync and PCY Sync at same time?  

best regards,
Leonardo

**Comment by jrabbit** [comment]
you could share an account and use a side process for it, but its not supported in the client?

**Comment by lesar** [comment]
> you could share an account 

yes
> and use a side process for it

you mean `taskd` on server

> but its not supported in the client?

I do not understand this: way the '?' you mean '!' and you mean that the client do not handle competing calls to taskd?  

Forgive my poor English.  

I need some more explanation

best regards,
Leonardo

**Comment by jrabbit** [comment]
taskd and taskwarrior do not support this usecase currently. you can approximate it by using a hack or "side process".
sharing an account would preclude using taskwarrior with personal or even just personal work todos unfortunately.

**Comment by lesar** [comment]
Thank you,  
perhaps overriding data.location like this alias 
`alias taskw='task rc.data.location=path1'`   
`alias taskme='task rc.data.location=path2'`  
give you multiple task env

but taskd do not get sync data from multiple user so I understand that  taskd and taskwarrior do not support this usecase currently.

regards
