### ISSUE TITLE
Taskwarrior list output formatting issue

### ISSUE THREAD

**Issue by MadHatter122312** [GothenburgBitFactory/taskserver#167]
I am a first time taskwarrior MacOS Catalina user, installed with brew:

`task --version
2.5.1`

When I run `task` output a list I get:

ID Age Description  Urg 
 1 16s dummy task 1    0
 2 12s dummy task 2    0
 3 8s  dummy task 3    0
 4 4s  dummy task 4    0

However, on my terminal task #2 and #4 are redacted!  I did not make any changes to the .taskrc

Is this default behavior?

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
