### ISSUE TITLE
Feature request: multiple task servers, with conditional routing/syncing

### ISSUE THREAD

**Issue by extemporalgenome** [GothenburgBitFactory/taskserver#168]
Related to GothenburgBitFactory/taskwarrior#2156 in terms of expanding sharing/syncing capabilities, it would be empowering to have the ability to keep both personal and work tasks on the same device, managed with the same configuration, yet have work-related tasks sync to one task-server, while syncing personal tasks (or all tasks) to a separate task-server, based on some kind of task-based filter.

Conversely, I would want the ability to prevent certain devices (work laptop) from being able to receive personal tasks during a sync. Along with GothenburgBitFactory/taskwarrior#2156, this could allow tasks to be shared with multiple colleagues, while keeping non-work tasks isolated, all based on task attributes (e.g. a "work" tag).

**Comment by 4kbt** [comment]
@tbabej -- is this concern a taskserver issue or a client issue? With my present understanding, it seems like a client issue. If clients can be configured to connect to multiple taskservers/task lists, the client needs the capability to handle the heterogeneous information. The taskserver can proceed unmodified.

Is there something broken about my understanding? Thanks!

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
