### ISSUE TITLE
run task server in foreground 

### ISSUE THREAD

**Issue by mygithubthrowaway** [GothenburgBitFactory/taskserver#169]
Hi,
I was wondering if there is a option for running task server in foreground, to achieve having logs in std-out (for docker, k8s etc).

Thanks

**Comment by jrabbit** [comment]
by default yes

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
