### ISSUE TITLE
[Feature] Add official dockerfile + dockercompose

### ISSUE THREAD

**Issue by jdorel** [GothenburgBitFactory/taskserver#170]
It would be awesome to add an official dockerfile + dockercompose so that installation is quick and easy. For example the following repo implements it : https://github.com/ogarcia/docker-taskd.

Should you agree with this, I'll be happy to work on it (i'll use it as an excuse to build a proper Dockerfile :) ).

**Comment by tamis-laan** [comment]
+1 currently in need of this myself.

**Comment by jakec-dev** [comment]
+1

**Comment by S1SYPHOS** [comment]
Would love to see this happening!

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
