### ISSUE TITLE
generating certificates causes crt_sign error

### ISSUE THREAD

**Issue by scmbradley** [GothenburgBitFactory/taskserver#171]
When I try to generate a certificate using the script `generate` I get the following error:

```
Signing certificate...
crt_sign: ASN1 parser: Value is not valid.

```

**Comment by scmbradley** [comment]
Generating the keys seems to be working fine, but the generation of the certificates doesn't work. That is, commenting out `rm ca.info` in `generate.ca` and running `certtool --generate-self-signed --load-privkey ca.key.pem --template ca.info --outfile ca.cert.pem` from the cli yields the same error.

**Comment by scmbradley** [comment]
This seems to happen with `master` and `1.2.0` branches. `certtool --version` gives 3.6.15.

The commands seem to work fine on my local machine (`certtool --version` 3.6.13).

**Comment by scmbradley** [comment]
A friendly anonymous Guest on the nearlyfreespeech.net member forums suggested that this behaviour is related to [this bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252548) and that the suggested workaround might help. I have not had time to test this hypothesis.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
