### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by langdon** [GothenburgBitFactory/taskserver#172]
I was just wondering if TLS SNI "should" work. I don't know a great way to test this (without a lot of work) and I couldn't find anything about it in the documentation.

Why do I ask? Because I would like to run taskd / taskserver in kubernetes / openshift but I don't want to deal with non-http port routing. Basically, kubernetes doesn't have great support for non-http traffic. However, it does support SNI routing so doing something like TLS/SNI on 443 to a task server *should* work but, I would prefer to limit my unknowns and make sure taskserver will work with SNI before introducing all the other variables :).

Related, as the world goes toward http as the "only" protocol, has anyone considered moving taskserver to a REST interface making ^^ basically not an issue?

I didn't see a better place in the "contributing" section to ask this question aside from an "issue" so apologies if this belongs somewhere else.

**Comment by jrabbit** [comment]
This sounds like the wrong approach. Work with "normal" tcp forwarding and swap out the networking components in k8s if they limit you here. As for SNI support, I think gnutls should do that for us already.

**Comment by langdon** [comment]
right.. the "right way" is as you describe.. but it is also a much less vanilla install which is much more prone to error. I am looking for a "in my basement" setup, not "high quality production". :)

re gnutls:  that was my hope so ill pursue on the assumption that taskserver should be ok already

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
