### ISSUE TITLE
Document the protocol

### ISSUE THREAD

**Issue by Oppen** [GothenburgBitFactory/taskserver#175]
It may be interesting to make alternative implementations, for example a simpler one that runs under a super-server that would handle the TLS encryption and connection for low load servers or one with pipes that allows for an easier implementation of hooks (e.g. unlocking a per-user encrypted directory on sync and locking it again on exit, for data-at-rest privacy).
However, this currently requires groking the source code, since the protocol description is nowhere to be found.

**Comment by jrabbit** [comment]
There's extensive documentation that can be found [on the RFC page](https://taskwarrior.org/docs/design/index.html)

**Comment by Oppen** [comment]
Oh, sorry, I couldn't find them.
