### ISSUE TITLE
Statistics request for non-release builds could provide `client: taskd <commit hash>`

### ISSUE THREAD

**Issue by bradyt** [GothenburgBitFactory/taskserver#178]
Currently, if a taskd client sends `type: statistics`, and gets a successful response (`code: 200`), apparently they only see the `client` field for release builds, like `client: taskd 1.1.0`. For other builds, the `client` field is omitted from the response.

It would be a nice to have if these taskd builds returned something like:

```
client: taskd d1fb597ce8b0b3cba3bf655e6a2525b92cb430b7
```

**Comment by tbabej** [comment]
Perhaps even a better format would be to include last tagged release, including the hash, if it was a non-release build, like this:
```
client: task 2.5.3 d1fb597ce8b0b3cba3bf655e6a2525b92cb430b7
```

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
