### ISSUE TITLE
Arrayed depends in tx.data is stringified in response

### ISSUE THREAD

**Issue by bradyt** [GothenburgBitFactory/taskserver#181]
I'm using Taskserver 1.1.0 and Taskwarrior 2.5.3.

I try `json.depends.array=yes`, and I import the following json into Taskwarrior:

```json
[
{"id":1,"description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"00000000-0000-0000-0000-000000000000","urgency":10},
{"id":2,"depends":"00000000-0000-0000-0000-000000000000","description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"11111111-1111-1111-1111-111111111111","urgency":-3}
]
```

Upon sync, the data lands successfully in `tx.data` at server, and has the following format:

```
{"description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"00000000-0000-0000-0000-000000000000"}
{"depends":["00000000-0000-0000-0000-000000000000"],"description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"11111111-1111-1111-1111-111111111111"}                                       
22222222-2222-2222-2222-222222222222
```

However, if I then clear my local `~/.task/*.data`, and sync again, I see the following in the logs at the server:

```
s: INFO Sending 'XXXXclient: taskd 1.1.0
code: 200
status: Ok

{"description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"00000000-0000-0000-0000-000000000000"}
{"depends":"[\"00000000-0000-0000-0000-000000000000\"]","description":"foo","entry":"20210101T000000Z","modified":"20210101T000000Z","status":"pending","uuid":"11111111-1111-1111-1111-111111111111"}
22222222-2222-2222-2222-222222222222

' (427 bytes)
```

It looks like Taskserver has erroneously converted `"depends":["00000000-0000-0000-0000-000000000000"]` to `"depends":"[\"00000000-0000-0000-0000-000000000000\"]"`.

And the result at local `pending.data` is the following:

```
[description:"foo" entry:"1609459200" modified:"1609459200" status:"pending" uuid:"00000000-0000-0000-0000-000000000000"]
[depends:"&open;\"00000000-0000-0000-0000-000000000000\"&close;" description:"foo" entry:"1609459200" modified:"1609459200" status:"pending" uuid:"11111111-1111-1111-1111-111111111111"]
```

I checked at `taskd 1.2.0 7f41114`, and this issue no longer exists. But I am hesitant to use this version yet, because I don't understand the implications of https://github.com/GothenburgBitFactory/taskserver/issues/177. Would team consider patching perhaps as 1.1.1 until I better understand issue 177.

This issue is probably a duplicate of the original, filed at https://github.com/GothenburgBitFactory/taskwarrior/issues/2689.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
