### ISSUE TITLE
gnutls-utils should be gnutls-bin for Ubuntu/Debian

### ISSUE THREAD

**Issue by nicolasshu** [GothenburgBitFactory/taskserver#185]
Hi!
Could you fix your guides for the installation process? The `gnutls-utils` should be the name for the Redhat, but for Ubuntu/Debian, it should be `gnutls-bin`

Thanks!

**Comment by nicolasshu** [comment]
This was opened as a pull request in another repo

https://github.com/GothenburgBitFactory/taskserver-setup/pull/11/commits/bb76109a19639dce0fed6fff20d225ed160f45b5

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
