### ISSUE TITLE
Unable to parse TLS packet header

### ISSUE THREAD

**Issue by ROODAY** [GothenburgBitFactory/taskserver#186]
I setup taskserver using this docker image: https://github.com/ogarcia/docker-taskd. I then exec'd into the image to create an organization and user and certs after setting the CN to tasks.rooday.com. The docker container exposes port 53589, which I reverse proxy with nginx with this config:

```
server {
    server_name tasks.rooday.com;
    location / {
        proxy_pass http://127.0.0.1:53589;
    }
}
```

And I use Cloudflare to handle DNS and proxy requests for rooday.com.

I followed the docs to copy the ca.cert.pem and the cert.pem and key.pem files for my user, and set up the client config as per the docs, but whenever I try to sync, either through the Ubuntu taskwarrior client or through the Android client Foreground: https://github.com/bgregos/foreground I get this error:
```
Handshake failed.  An unexpected TLS packet was received.
Sync failed.  Could not connect to the Taskserver.
```
(on Foreground the error is `Unable to parse TLS packet header`).

Looking through the other issues here on GitHub, it seems that when taskserver is proxied behind nginx or cloudflare there are issues, but has anyone been able to resolve this?

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
