### ISSUE TITLE
Regarding interprete the test results, mention all.log

### ISSUE THREAD

**Issue by stappersg** [GothenburgBitFactory/taskserver#188]
Hi,

Somewhere down https://gothenburgbitfactory.github.io/taskserver-setup/ is this

```text

Interprete the results

This example shows that all 2,920 tests pass. If you see test failures, stop and report them.

Note that there are some unit tests that fail if you have not built the latest commit.
Seeing 4 test failures may mean all is well. Seeing 30 failures does not.
```

I have
```text
    ...
[  98%] Building CXX object test/CMakeFiles/text.t.dir/test.cpp.o
[100%] Linking CXX executable text.t
[100%] Built target text.t
stappers@hc4:/usr/src/taskserver/test
$ ./run_all
Pass:     2921
Fail:        1
Skipped:     0
Runtime:     5 seconds
stappers@hc4:/usr/src/taskserver/test
$ ./run_all --help
Pass:     2921
Fail:        1
Skipped:     0
Runtime:     5 seconds
stappers@hc4:/usr/src/taskserver/test
$ 
```

So I have a failure, don't know what it is and  don't know how to zoom in.

Please mention the file `all.log` nearby the _ If you see test failures, stop and report them._
So people have a clue where to look next.

Adding to the _task server setup guide_ where to report the test failures would also be good thing.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
