### ISSUE TITLE
How do you map a client certificate/key to a user ID

### ISSUE THREAD

**Issue by dsedgmen** [GothenburgBitFactory/taskserver#193]
Hi 

From the documentation and the client certificate generation script.
It looks like it does not matter which client certificate is used just the user uuid provided by the client. 

Is there a way to map the user uuid to the client certificate? 
If not is there a way to log which client certificate was used to access a user?

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
