### ISSUE TITLE
taskd server exits without errors when config doesn't exist

### ISSUE THREAD

**Issue by ptrcnull** [GothenburgBitFactory/taskserver#194]
as in the title: when running `taskd server --data /somepath` and /somepath/config doesn't exist, taskd just exits with code 0 and no error message

**Comment by Remmy** [comment]
Hi ptrcnull, this is fixed in 1.2.0 (development version). Commit bbd42468 of 2016-03-26

**Comment by ptrcnull** [comment]
cool, thanks! of course, feel free to close it when it gets merged to stable

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
