### ISSUE TITLE
tx.data with '"wait":"20380120T000000Z"' and above results in "Unrecognized Taskwarrior file format or blank line in data." when trying to sync

### ISSUE THREAD

**Issue by s7hoang** [GothenburgBitFactory/taskserver#195]
# test data:
## tx.data (stored on server):
    {"description":"test-description","end":"20220727T184341Z","entry":"20220519T095755Z","modified":"20220727T184341Z","priority":"M","project":"test-project","status":"completed","uuid":"309e28fb-da7c-4654-85c9-d66993a1b3f1","wait":"20380120T000000Z"}

## result on sync with empty task client:

    Unrecognized Taskwarrior file format or blank line in data.

# diagnostics
## taskd diagnostics

    taskd 1.1.0
        Platform: Linux
        Hostname: VBox-Arch

    Compiler
         Version: 10.1.0
            Caps: +stdc +stdc_hosted +200809 +200809 +LP64 +c8 +i32 +l64 +vp64 +time_t64
      Compliance: C++11

    Build Features
           Built: Jul  7 2020 17:11:00
           CMake: 3.17.3
         libuuid: libuuid + uuid_unparse_lower
       libgnutls: 3.6.14
      Build type: Release

    Configuration
       TASKDDATA:
            root: /var/lib/taskd (readable)
          config: /var/lib/taskd/config (readable)
              CA: /var/lib/taskd/ca.cert.pem (readable)
     Certificate: /var/lib/taskd/server.cert.pem (readable)
             Key: /var/lib/taskd/server.key.pem (readable)
             CRL: /var/lib/taskd/server.crl.pem (readable)
             Log: /var/lib/taskd/taskd.log (found)
        PID File: /var/lib/taskd/taskd.pid (missing)
          Server: 192.168.1.99:53589
     Max Request:  bytes
         Ciphers:
           Trust: Bad value - see 'man taskdrc'

## task --version

    2.6.2

# other notes:

  Any wait entry below `20380118T271407Z` seems to sync fine.

  example:
  `20380201T000000Z` = fail
  `20380118T271408Z` = fail

  Exceptionally:
  `20380119T000000Z` = success (for some reason)

  Notably however is that the hour is wrong when the wait date is
  `20380118T271407Z`:

      task <id>
      ...
      Waiting until 2038-01-18 22:14:07
      ...

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
