### ISSUE TITLE
make uninstall

### ISSUE THREAD

**Issue by vsl-iil** [GothenburgBitFactory/taskserver#197]
I'm glad that this repo even includes unit tests for this great program, however, it would be nice if you added a way to uninstall it. Undoing make commands manually isn't fun. Thank you.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
