### ISSUE TITLE
taskd init should use XDG filesystem path to avoid specifying data

### ISSUE THREAD

**Issue by gl-yziquel** [GothenburgBitFactory/taskserver#199]
Ideally, the `taskd init` command should (in my opinion) have a convention over configuration approach and make the --data option optional with a sensible default. The XDG specification should provide a guide as to how this should be configured. $XDG_DATA_HOME should be used.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
