### ISSUE TITLE
taskd init --data should create data folder

### ISSUE THREAD

**Issue by gl-yziquel** [GothenburgBitFactory/taskserver#200]
Currently, running `taskd init --data some_folder` complains if `some_folder`does not exist. By default, creation of such a folder should be attempted.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
