### ISSUE TITLE
newer recurrence format gives a 500 error, says the format is incorrect

### ISSUE THREAD

**Issue by zaphodb2002** [GothenburgBitFactory/taskserver#201]
So if you format your recurrences using the P1D format, taskd will reject them.  I renamed all P1D to 1d and the error no longer occurs.  This happens in Task.cpp, there's even a comment about it.  Just needs to be accounted for.  I'm gonna take a whack at fixing this myself, though I'm not super familiar with C++.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
