### ISSUE TITLE
[TD-1] taskdctl graceful - spawns a new taskd and SIGUSR1 is ineffective

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#3]
_Renato Alves on 2014-01-23T11:46:18Z says:_ 

 *taskctl graceful* doesn't wait for any action from the running taskd instance and immediately spawns a new taskd instance which will stop with a "Address already in use" error.

This also causes taskctl to get confused as the PID file will point to the newly spawned taskd which is no longer running, while the old one is still.

Finally SIGUSR1 is ineffective because the old server doesn't reload its configuration.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
