### ISSUE TITLE
[TD-41] Systemd unit configuration

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#43]
_Roman Inflianskas on 2014-02-28T19:50:34Z says:_ 

 I propose to include systemd unit configuration file into the source or at least into the docs (I'm not sure who should be responsible for writing those things: developer or packager). Here is my simple version of unit config and sysconfig file.

**Comment by pbeckingham** [comment]
[TD-41_taskd.service.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755334/TD-41_taskd.service.txt)
[TD-41_taskd.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755335/TD-41_taskd.txt)
