### ISSUE TITLE
[TD-45] diag.cpp:163:7: error: token ""2.12.23"" is not valid in preprocessor expressions

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#47]
_Jochen Sprickerhof on 2014-03-06T23:02:54Z says:_ 

 Got a compiler error. The attached patch fixes this.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-03-06T23:02:54Z
Modified: 2014-03-07T00:19:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-03-07T00:19:04Z says:_ 

 Patch also applied to Taskwarrior.  Thank you!

I have added you to the AUTHORS file in each project.

**Comment by pbeckingham** [comment]
[TD-45_0001-Fix-preprocessor-define.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755333/TD-45_0001-Fix-preprocessor-define.patch.txt)
