### ISSUE TITLE
[TD-48] Empty username is not an error

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#49]
_Ben Boeckel on 2014-04-25T02:47:13Z says:_ 

 If the server, for whatever reason, cannot read a configuration file, the expected username comes back empty. Deny all empty usernames to prevent this (they make no sense anyways).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-04-25T02:47:13Z
Modified: 2014-04-25T13:59:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-25T13:59:26Z says:_ 

 Patch applied.  Thank you.

**Comment by pbeckingham** [comment]
[TD-48_0001-Ensure-that-the-username-is-non-empty.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755332/TD-48_0001-Ensure-that-the-username-is-non-empty.patch.txt)
