### ISSUE TITLE
[TD-51] Taskd should listen on all matching adresses and interfaces

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#52]
_Anatolij Zelenin on 2014-05-07T20:11:05Z says:_ 

 *Current behaviour:*

Taskd only listens on one address. (For me it's the IPv6 address) So users who are using IPv4 can not reach the server and can not sync.

*Expected behaviour:*

Taskd should listen on all addresses and not only on the first which match the server line.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-05-07T20:11:05Z
Modified: 2015-05-14T01:58:44Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-05-03T03:59:59Z says:_ 

 Interface is chosen using either the 'family' configuration setting, or by specfiying and IPv4 or IPv6 address.  Details here: http://taskwarrior.org/docs/taskserver/protocol.html

**Comment by taskwarrior** [comment]
_Johannes Wienke on 2015-05-13T13:39:31Z says:_ 

 I am stuck with exactly the same situation and I can't see how to solve this with the configuration. My hosts file has both, an IPv4 and an IPv6 address for the host name that is configured for the taskd server. The family option is left blank. In the end, the server only listens on IPv6.

Also, when looking at the source code, I see no way this should work. Only one server socket is created at all and in the case of an IPv6 socket, the option IPV6_V6ONLY is not set to false. So how is this supposed to listen for IPv4, in case the IPv6 address is selected?

**Comment by taskwarrior** [comment]
_Renato Alves on 2015-05-13T14:44:49Z says:_ 

 Hi Johannes,

Binding to multiple interfaces is currently not supported.
It's planned for a future version of taskd as it will require significant changes to the codebase.

In the meantime, you could perhaps use a proxy or tunnel to channel traffic from one protocol to the other.
[This ServerFault question|http://serverfault.com/questions/276515/use-iptables-to-forward-ipv6-to-ipv4] provides two possible solutions.

**Comment by taskwarrior** [comment]
_Johannes Wienke on 2015-05-13T14:50:58Z says:_ 

 Thanks for the information. I'll have a look at that solution.

Apart from that, I think this is an important feature nowadays. Maybe it would be easy to use dual-stack in cases where this is available as a first solution to at least listen on ipv4 and v6 in parallel without changing the architecture.

**Comment by taskwarrior** [comment]
_Johannes Wienke on 2015-05-13T16:05:18Z says:_ 

 This patch tries to use the dual stack in case of IPv6 connections. This only enables listening on IPv4 as well, when the listen address is the IPv6 Wildcard :: , ie. the server configuration should look like server=:::<someport>

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-05-14T01:58:44Z says:_ 

 Thank you.  I read about this recently, but didn't get around to trying it.  Much appreciated.  Modified patch applied.

**Comment by pbeckingham** [comment]
[TD-51_0001-If-binding-to-an-IPv6-address-try-to-use-dual-stack.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755331/TD-51_0001-If-binding-to-an-IPv6-address-try-to-use-dual-stack.patch.txt)
