### ISSUE TITLE
[TD-52] No errors in log in case of "No space left on device", but task data corrupted

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#53]
_Rainer Müller on 2014-05-14T16:12:37Z says:_ 

 I experienced a problem with taskd, when the volume with TASKDDATA was full: "No space left on device". My tx.data is now incomplete JSON due to being cut-off somewhere and leads to "Unrecognized taskwarrior file format" when trying to sync again.

However, taskd.log does not contain any messages about the full disk and even indicated to the client that this was a successful sync. Only the next request afterwards failed with "Unrecognized taskwarrior file format".

Attached is an anonymized excerpt from taskd.log showing the messages logged for the last request before the sync began to reply with errors.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-05-14T16:12:37Z
Modified: 2016-10-30T16:22:12Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-10-30T16:22:12Z says:_ 

 Fixed.  Thank you.

**Comment by pbeckingham** [comment]
[TD-52_taskd.log.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755329/TD-52_taskd.log.txt)
