### ISSUE TITLE
[TD-59] Taskd segfaults when syncing task whose annotations value is not a json array.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#60]
_Felix Martin on 2014-06-18T18:58:27Z says:_ 

 Consider the following backlog.data file:

```
{"annotations": `"entry": "20140531T180959Z", "description": "Should not be too difficult with the new backend."`, "status": "pending", "description": "Add dependencies for tasks.", "entry": "20140522T183926Z", "uuid": "1ed6b92a-8e13-4293-80d0-6c7945772ae3"}
```

Note that annotations value is a object and not an array. But taskd will assume this and therefore segfault.

I have tried to push a possible fix to origin 1.0.1 but I did not know which user credentials to provide. Help on that would be appreciated.

See the attached patch for a simple fix. Feedback here is welcome too.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-18T18:58:27Z
Modified: 2015-04-27T03:12:34Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-06-18T23:06:57Z says:_ 

 Hi Felix,

Thanks for the bug and the patch.  I will take a look at this shortly, and act on it.  I have a question for you:  What client and version are you using?  In other words, why is your annotations JSON an object, not an array?

That said, the patch looks good whatever the answer, but I am curious.

Regarding the 1.0.1 push, no one has push access.  We shut down access after some sub-optimal experiences with unwanted pushes.  We are now using a patch-only model.  For folks who submit a lot of patches, we create a Stash account, then use pull requests.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-06-18T23:07:36Z says:_ 

 I should have also mentioned that the 1.0.1 branch is there for emergency use.  Development is on 1.1.0.

**Comment by taskwarrior** [comment]
_Felix Martin on 2014-06-19T06:59:11Z says:_ 

 Hi Paul,

thanks for your answer. I have just realized that my previous example is invalid json and taskd returns with the correct error message. Please test with this example instead:

{code}
{"status": "pending", "description": "Add dependencies for tasks.", "entry": "20140522T183926Z", "annotations": "[{u'entry': u'20140531T180959Z', u'description': u'Should not be too difficult with the new backend.'}]", "uuid": "1ed6b92a-8e13-4293-80d0-6c7945772ae3"}
{code}

My annotions JSON is a string because I am using a self written python sync client which syncs between my django application and taskserver. I was playing around to find the best way to serialize and deserialize annotations and that is where I got this result.

So I was not using any official version of taskwarrior.

**Comment by taskwarrior** [comment]
_Felix Martin on 2014-06-19T07:05:48Z says:_ 

 Providing a _valid_ JSON object to annotations also works to demonstrate the issue:

{code}
{"annotations": {"foo": "bar"}, "uuid": "1ed6b92a-8e13-4293-80d0-6c7945772ae3"}
{code}

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-06-19T11:07:47Z says:_ 

 The Server doesn't just accept any old JSON you throw at it.  It must conform to the spec: http://taskwarrior.org/docs/json.html.  For example, your annotations look like this, which is wrong:

```
  ... "annotations": "[ ... ]"
```

That said, it should not segfault.

**Comment by taskwarrior** [comment]
_Felix Martin on 2014-06-19T12:52:03Z says:_ 

 Hi Paul,

I should be more careful with my language when speaking about technical subjects.

I understand that taskd will reject JSON which does not conform to the spec. What I wanted to express is that I _was_ failing to create JSON which conforms to the spec at first and thus discovered the bug.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-06-19T13:07:00Z says:_ 

 Thanks Felix, understood.  I need to fix this, and make it more robust.

I'm trying to serve two purposes here - figure out what I need to fix, and also make sure your project is succeeding.  Looks like you have that one covered.

P

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-04-27T03:12:34Z says:_ 

 Thanks!

**Comment by pbeckingham** [comment]
[TD-59_Task.cpp.diff.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755327/TD-59_Task.cpp.diff.txt)
