### ISSUE TITLE
[TD-60] Make PKI scripts easier to use

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#61]
_viq on 2014-06-21T07:52:25Z says:_ 

 This diff does a couple of things:
  * changes /bin/bash to /bin/sh so it works on OpenBSD (and it does work with plain old sh)
  * moves variables used in scripts to a separate file and sources the file when running scripts, making it much easier to create certs for own environment
  * ASCIIfy above variables, makes for easier life
  * try and extract hostname and all IPs of host it's running on in generate.server to make life easier - this one will probably need some thinking/discussion. Or I could take that part out into vars as well.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-21T07:52:25Z
Modified: 2014-06-24T20:57:37Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-06-21T11:37:38Z says:_ 

 ASCIIfy?  Why does it need to be ASCII?  ASCII is obsolete, and changing the name is wrong.

**Comment by taskwarrior** [comment]
_viq on 2014-06-22T13:09:13Z says:_ 

 That's the change I care the least about, I'll upload soon a patch without this, also trying to move the IP and hostname detection out to vars.

What I'm more interested in is what you think about the rest of the changes, and the general idea?

**Comment by taskwarrior** [comment]
_viq on 2014-06-24T14:41:01Z says:_ 

 How about this version of the patch then?

  *  changes /bin/bash to /bin/sh so it works on OpenBSD (and it does work with plain old sh)
  *  moves variables used in scripts to a separate file and sources the file when running scripts, making it much easier to create certs for own environment
  *  try and extract hostname and all IPs of host it's running on in generate.server to make life easier. Allow overriding in vars.

**Comment by taskwarrior** [comment]
_viq on 2014-06-24T14:41:25Z says:_ 

 Updated version of patch

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-06-24T20:57:37Z says:_ 

 Patch applied with the following changes:
*  changed "ifconfig -A" to "ifconfig -a"
*  upper-cased script variable names (not loop vars though)
*  added comment to "vars" file
*  Updated ChangeLog, AUTHORS, NEWS

**Comment by pbeckingham** [comment]
[TD-60_pki.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755325/TD-60_pki.patch.txt)
[TD-60_taskd-pki.diff.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755326/TD-60_taskd-pki.diff.txt)
