### ISSUE TITLE
[TD-5] Synchronize settings via taskd

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#7]
_Anatolij Zelenin on 2014-02-07T15:31:32Z says:_ 

 # Use cases

I want to have consistent settings all over my devices so I can work in a comfortable environment. Also I want to sync my Mirakel settings across the devices.
# Protocol changes

The taskd protocol must be extended to support this feature. It should be downward compatible. 

The client MUST check if the taskd-version supports synchronizing settings.
## Header

The client MUST announce that it want to sync the settings. This has the benefit, that it is backward compatible and the user must actively start the sync of the settings. For example the command could be <pre>task sync settings</pre>

The type is changed to sync_settings instead of sync.
<pre>
* ---8<----
<size>type: sync_settings
org: <organization>
user:<user>
key: <password>
client: <client>
protocol: <version>
* payload-
* ---8<----
</pre>
## Payload

The payload consists of lines of JSON-objects. Every object represents a namespace for the settings.

<pre>
* ---8<----
* header-

{"taskd":{"server":"example.com:6544","credentials"="<organization>>\/<user>\/<password>",…`
{"color":{"header":"yellow"`
* ---8<----
</pre>

When taskd merges the settings it must somehow determine which setting is more up to date. One possibility would be to save for every namespace a timestamp. It would be just an additional variable:

<pre>{"color":{"header":"yellow","last_change":"20140107T150000Z"`</pre>
# Annotations

I tried to be consistent with the other documentation, but it would be more beautiful if we use one JSON-object instead of one object per line. Then the example will look like the following:

<pre>
* ---8<----
* header-

{"taskd":{"server":"example.com:6544","credentials"="<organization>>\/<user>\/<password>",…}, "color":{"header":"yellow"`
* ---8<----
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-02-07T15:31:32Z
Modified: 2015-02-28T17:29:14Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-07T15:38:29Z says:_ 

 Good idea, nicely thought out, nicely documented.

First there is a taskd 1.1.0 release coming up soon, which is for bugs and minor improvements.  Let's put this in the 1.2.0 version.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-28T17:29:14Z says:_ 

 Moving to backlog, because I don't want to try and plan major releases in advance, because it always changes.

**Comment by pbeckingham** [comment]
No plans to sync anything other than tasks.
