### ISSUE TITLE
[TD-71] Slow Clients make Others Wait

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#72]
_Jack on 2014-08-31T22:47:33Z says:_ 

 Here are two syncs from the FreeCinc log. Both accounts actually belong to me. The first, which I will call "A" has a 41kB tx.data file (normal usage) and syncs every 7 minutes from Mirakel. "A" took a whopping 41 seconds to service. At the time of this log, my cell phone was in a spotty coverage area. Could that explain the 41 seconds?

The second account, which I will call "B", is a test account in the amazon cloud. Every minute it adds a task with a short, randomized description and syncs. It usually hits the taskd log at 12 seconds past the minute due to differences in each server's respective clock. But in this case it actually timed out (I give it a five second window to sync, then pull the plug).

Here's what I suspect is happening. (Fill me in if I'm wrong about how taskd handles multitasking/threading)

* "A" calls up taskd and begins to sync. Being in spotty cell reception at the time, it takes a while
* Meanwhile, "B" calls up taskd and gets in the queue to sync
* Once "A" is done, "B" gets a chance to sync.
* "B" has fast internet and syncs quickly as soon as "A" is done.

A couple concerns:

1. If slow internet connections actually make other clients wait (I don't know if this is how it works--please fill me in), this could limit how many clients a single server can handle.
2. I'm not sure if this is by design or oversight, but "A" has all matching timestamps. In a way this is good because it shows everything together. But on the other hand it doesn't tell me whether 16:52:17 was the start of the sync or the end. (I'm going to assume the end of the sync, since "B" also at 16:52:17)

{code}
2014-08-31 16:52:17 DEBUG client 'Mirakel 2.7.1' allowed by 'all'
2014-08-31 16:52:17 [1694] 'sync' from 'FreeCinc/freecinc_A******' using 'Mirakel 2.7.1' at :0
2014-08-31 16:52:17 [1694] Client key '[filtered]' 0
2014-08-31 16:52:17 [1694] Loaded 449 records
2014-08-31 16:52:17 [1694] Branch point: [filtered] --> 448
2014-08-31 16:52:17 [1694] Subset 0 tasks
2014-08-31 16:52:17 [1694] Stored 0 tasks, merged 0 tasks
2014-08-31 16:52:17 [1694] Sync key '[filtered]' still valid
2014-08-31 16:52:17 [1694] No change
2014-08-31 16:52:17 [1694] Serviced in 41.464794s
2014-08-31 16:52:17 DEBUG client 'task 2.3.0' allowed by 'all'
2014-08-31 16:52:17 [1695] 'sync' from 'FreeCinc/freecinc_B******' using 'task 2.3.0' at :0
2014-08-31 16:52:17 [1695] Client key '[filtered]' 1
2014-08-31 16:52:17 [1695] Loaded 26444 records
2014-08-31 16:52:17 [1695] Branch point: [filtered] --> 26443
2014-08-31 16:52:17 [1695] Subset 0 tasks
2014-08-31 16:52:17 [1695] Stored 1 tasks, merged 0 tasks
2014-08-31 16:52:17 [1695] New sync key '[filtered]'
2014-08-31 16:52:17 [1695] Wrote 2
2014-08-31 16:52:17 [1695] Serviced in 0.072355s
{code}

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-08-31T22:47:33Z
Modified: 2015-02-07T19:59:14Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-08-31T23:19:14Z says:_ 

 Great data, well presented, thank you Jack.

Essentially your analysis is spot-on.  Taskd is a single-threaded server, and one client will block another.  We have plans to address this, but have never seen it have such an enormous impact as this.  The plans are:

1. Implement user-level locking on the data.  This would allow launching two or more daemons to manage one $TASKDDATA instance.  Users would have daemon-instance affinity (they are configured per port), which means the problem can still occur, but not for everyone.

2. Upgrade the server to be a threaded server, with a configurable thread-pool, ensuring smoother data flow.  This then gives you more tuning options.  [2] requires [1].

Once these are implemented, the problem you describe is mitigated, in that the servers and other users are not queued up waiting for a slow client, thread-pool size notwithstanding.

Your 41s sync I assume is an extreme case, but with mobile devices, is it really exceptional?  There is a lot of TLS handshaking going on, but once past that, taskd operates with a single upload transaction, then a single response transaction.  I am surprised by the 2014-08-31 16:52:17 timestamp for every entry, and I expect that 41s to be reflected in the spread of timestamps reported.  That's either a bug, or behavior I'm unaware of.

**Comment by taskwarrior** [comment]
_Jack on 2014-09-01T03:32:37Z says:_ 

 I have requested a feature from Mirakel to randomize the sync time: https://mirakel.atlassian.net/browse/MIR-514

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
