### ISSUE TITLE
[TD-85] Thread the server

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#85]
_Paul Beckingham on 2014-12-29T18:58:05Z says:_ 

 Process each incoming request in a separate thread.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-12-29T18:58:05Z
Modified: 2015-02-28T18:26:20Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-28T18:26:20Z says:_ 

 I would prefer to raise the C++11 compiler requirements and use std::thread, rather than pthreads.

**Comment by Oppen** [comment]
For this kind of process I think it would make more sense to use asynchronous programming rather than threads.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
