### ISSUE TITLE
[TD-88] Use a single .pem file

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#88]
_Jack Laxson on 2015-01-29T15:38:19Z says:_ 

 PEM files can have more than one key block, if taskwarrior supported this it would reduce how many commands a user must run to configure sync.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-29T15:38:19Z
Modified: 2015-01-29T15:49:21Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2015-01-29T15:48:44Z says:_ 

 I agree that this might make setting up sync less error prone: 1 file, 1 action.

Not exactly a .pem file but [here's another example|http://mirakel.azapps.de/taskwarrior.html#create-your-own-config-file].

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
