### ISSUE TITLE
[TD-7] taskd-1.0.0 should complain about missing ca.cert.pem with self-signed certificates

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#9]
_Renato Alves on 2014-01-22T20:52:48Z says:_ 

 If taskd is started with self-signed certificates but a ca.cert.pem is not defined, taskd should complain or at least write a warning in the logfile.

Since it's possible to distinguish a self-signed certificate from a trusted one, this error could be silenced in the trusted-cert case.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-01-22T20:52:48Z
Modified: 2015-02-28T17:29:55Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-25T23:00:41Z says:_ 

 Not sure how I distinguish between a self-signed cert and a trusted one, other than by validating it.  Maybe that is the answer - the server should validate it's own certs on startup.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
