### ISSUE TITLE
[TD-92] »taskd config« only checks the end of the key when changing config entries

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#92]
_Dominik Heidler on 2015-03-09T19:44:48Z says:_ 

 Steps to reproduce:

{code}
    % taskd init
    % taskd config --force server.key server.key.pem
    % taskd config --force client.key client.key.pem
    % cat /var/lib/taskd/config
    server.key=server.key.pem
    client.key=client.key.pem
    [...]
    % taskd config --force key foo.pem
    % cat /var/lib/taskd/config
    key=foo.pem
    key=foo.pem
    [...]
{code}

Patch is attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-03-09T19:44:48Z
Modified: 2015-03-09T21:28:02Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-09T21:28:02Z says:_ 

 Good catch, good patch.  Thank you.

**Comment by pbeckingham** [comment]
[TD-92_edit_substring.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755320/TD-92_edit_substring.patch.txt)
