### ISSUE TITLE
[TD-99] Manual page of taskd has hyphen instead minus sign "-".

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#99]
_Sebastien Badia on 2015-07-16T12:42:25Z says:_ 

 Hi,

The manual page of taskd has hyphen instead minus sign "-"
please, see the attached patch.

Thanks!

Seb

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-07-16T12:42:25Z
Modified: 2015-12-22T21:06:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-07-19T13:18:22Z says:_ 

 Thanks for the patch!  I added you to the AUTHORS file.

**Comment by taskwarrior** [comment]
_Sebastien Badia on 2015-12-22T21:06:26Z says:_ 

 thanks!

**Comment by pbeckingham** [comment]
[TD-99_fix-man-minus-sign.patch.txt](https://github.com/GothenburgBitFactory/taskserver/files/1755319/TD-99_fix-man-minus-sign.patch.txt)
